export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const ROBOTS_REQUEST_PEDING = 'ROBOTS_REQUEST_PEDING';
export const ROBOTS_REQUEST_SUCCESS = 'ROBOTS_REQUEST_SUCCESS';
export const ROBOTS_REQUEST_FAILED = 'ROBOTS_REQUEST_FAILED';
